[versions]
core-name = "VMTULibraries"
core-group = "top.vmctcn.vmtu.libraries"
core-version = "0.4.3"

archive-patcher-applier = "1.2"
log4j = "2.26.1"
jetbrains-annotations = "26.1.0"

commons-io = "2.22.0"
gson = "2.14.0"

[libraries]
archive-patcher-applier = { module = "net.runelite.archive-patcher:archive-patcher-applier", version.ref = "archive-patcher-applier" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
